image: python:latest

move:
  script:
    - mkdir .public
    - cp -r * .public/

deploy_to_pages:
  stage: deploy
  script:
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
