image: python:latest

run:
  script:
    - python fizz_buzz.py 100 fizz buzz > logging.txt
  artifacts:
    paths:
      - logging.txt

run_tests:
  script:
    - python fizz_buzz.py 100 fizz buzz | python3 test_fizz_buzz.py fizz buzz
